language:
  - c++
dist:
  - xenial
os:
  - linux
sudo:
  - required
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:fkrull/deadsnakes -y
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-5 g++-5 libcurl4-openssl-dev doxygen cmake libpython3.6-dev
script:
  - mkdir build && cd build
  - cmake .. -G "Unix Makefiles" -DCMAKE_C_COMPILER="gcc-5" -DCMAKE_CXX_COMPILER="g++-5" -DCMAKE_BUILD_TYPE=Debug -DGEARBOX_ENABLE_TESTS=ON -DGEARBOX_BUILD_DOCUMENTATION=ON
  - make

