#include "librt_file.h"

#include <unordered_map>
#include <experimental/string_view>

using namespace librt;

namespace
{
    using string_t = std::experimental::string_view;
    const std::unordered_map<string_t , File::MIMEType> mimeTypes {{
        {".323",                    { 0, "text/h323" } },
        {".3g2",                    { 1, "video/3gpp2" } },
        {".3gp",                    { 2, "video/3gpp" } },
        {".3gp2",                   { 3, "video/3gpp2" } },
        {".3gpp",                   { 4, "video/3gpp" } },
        {".7z",                     { 5, "application/x-7z-compressed" } },
        {".aa",                     { 6, "audio/audible" } },
        {".AAC",                    { 7, "audio/aac" } },
        {".aaf",                    { 8, "application/octet-stream" } },
        {".aax",                    { 9, "audio/vnd.audible.aax" } },
        {".ac3",                    { 10, "audio/ac3" } },
        {".aca",                    { 11, "application/octet-stream" } },
        {".accda",                  { 12, "application/msaccess.addin" } },
        {".accdb",                  { 13, "application/msaccess" } },
        {".accdc",                  { 14, "application/msaccess.cab" } },
        {".accde",                  { 15, "application/msaccess" } },
        {".accdr",                  { 16, "application/msaccess.runtime" } },
        {".accdt",                  { 17, "application/msaccess" } },
        {".accdw",                  { 18, "application/msaccess.webapplication" } },
        {".accft",                  { 19, "application/msaccess.ftemplate" } },
        {".acx",                    { 20, "application/internet-property-stream" } },
        {".AddIn",                  { 21, "text/xml" } },
        {".ade",                    { 22, "application/msaccess" } },
        {".adobebridge",            { 23, "application/x-bridge-url" } },
        {".adp",                    { 24, "application/msaccess" } },
        {".ADT",                    { 25, "audio/vnd.dlna.adts" } },
        {".ADTS",                   { 26, "audio/aac" } },
        {".afm",                    { 27, "application/octet-stream" } },
        {".ai",                     { 28, "application/postscript" } },
        {".aif",                    { 29, "audio/aiff" } },
        {".aifc",                   { 30, "audio/aiff" } },
        {".aiff",                   { 31, "audio/aiff" } },
        {".air",                    { 32, "application/vnd.adobe.air-application-installer-package+zip" } },
        {".amc",                    { 33, "application/mpeg" } },
        {".anx",                    { 34, "application/annodex" } },
        {".apk",                    { 35, "application/vnd.android.package-archive" } },
        {".application",            { 36, "application/x-ms-application" } },
        {".art",                    { 37, "image/x-jg" } },
        {".asa",                    { 38, "application/xml" } },
        {".asax",                   { 39, "application/xml" } },
        {".ascx",                   { 40, "application/xml" } },
        {".asd",                    { 41, "application/octet-stream" } },
        {".asf",                    { 42, "video/x-ms-asf" } },
        {".ashx",                   { 43, "application/xml" } },
        {".asi",                    { 44, "application/octet-stream" } },
        {".asm",                    { 45, "text/plain" } },
        {".asmx",                   { 46, "application/xml" } },
        {".aspx",                   { 47, "application/xml" } },
        {".asr",                    { 48, "video/x-ms-asf" } },
        {".asx",                    { 49, "video/x-ms-asf" } },
        {".atom",                   { 50, "application/atom+xml" } },
        {".au",                     { 51, "audio/basic" } },
        {".avi",                    { 52, "video/x-msvideo" } },
        {".axa",                    { 53, "audio/annodex" } },
        {".axs",                    { 54, "application/olescript" } },
        {".axv",                    { 55, "video/annodex" } },
        {".bas",                    { 56, "text/plain" } },
        {".bcpio",                  { 57, "application/x-bcpio" } },
        {".bin",                    { 58, "application/octet-stream" } },
        {".bmp",                    { 59, "image/bmp" } },
        {".c",                      { 60, "text/plain" } },
        {".cab",                    { 61, "application/octet-stream" } },
        {".caf",                    { 62, "audio/x-caf" } },
        {".calx",                   { 63, "application/vnd.ms-office.calx" } },
        {".cat",                    { 64, "application/vnd.ms-pki.seccat" } },
        {".cc",                     { 65, "text/plain" } },
        {".cd",                     { 66, "text/plain" } },
        {".cdda",                   { 67, "audio/aiff" } },
        {".cdf",                    { 68, "application/x-cdf" } },
        {".cer",                    { 69, "application/x-x509-ca-cert" } },
        {".cfg",                    { 70, "text/plain" } },
        {".chm",                    { 71, "application/octet-stream" } },
        {".class",                  { 72, "application/x-java-applet" } },
        {".clp",                    { 73, "application/x-msclip" } },
        {".cmd",                    { 74, "text/plain" } },
        {".cmx",                    { 75, "image/x-cmx" } },
        {".cnf",                    { 76, "text/plain" } },
        {".cod",                    { 77, "image/cis-cod" } },
        {".config",                 { 78, "application/xml" } },
        {".contact",                { 79, "text/x-ms-contact" } },
        {".coverage",               { 80, "application/xml" } },
        {".cpio",                   { 81, "application/x-cpio" } },
        {".cpp",                    { 82, "text/plain" } },
        {".crd",                    { 83, "application/x-mscardfile" } },
        {".crl",                    { 84, "application/pkix-crl" } },
        {".crt",                    { 85, "application/x-x509-ca-cert" } },
        {".cs",                     { 86, "text/plain" } },
        {".csdproj",                { 87, "text/plain" } },
        {".csh",                    { 88, "application/x-csh" } },
        {".csproj",                 { 89, "text/plain" } },
        {".css",                    { 90, "text/css" } },
        {".csv",                    { 91, "text/csv" } },
        {".cur",                    { 92, "application/octet-stream" } },
        {".cxx",                    { 93, "text/plain" } },
        {".dat",                    { 94, "application/octet-stream" } },
        {".datasource",             { 95, "application/xml" } },
        {".dbproj",                 { 96, "text/plain" } },
        {".dcr",                    { 97, "application/x-director" } },
        {".def",                    { 98, "text/plain" } },
        {".deploy",                 { 99, "application/octet-stream" } },
        {".der",                    { 100, "application/x-x509-ca-cert" } },
        {".dgml",                   { 101, "application/xml" } },
        {".dib",                    { 102, "image/bmp" } },
        {".dif",                    { 103, "video/x-dv" } },
        {".dir",                    { 104, "application/x-director" } },
        {".disco",                  { 105, "text/xml" } },
        {".divx",                   { 106, "video/divx" } },
        {".dll",                    { 107, "application/x-msdownload" } },
        {".dll.config",             { 108, "text/xml" } },
        {".dlm",                    { 109, "text/dlm" } },
        {".doc",                    { 110, "application/msword" } },
        {".docm",                   { 111, "application/vnd.ms-word.document.macroEnabled.12" } },
        {".docx",                   { 112, "application/vnd.openxmlformats-officedocument.wordprocessingml.document" } },
        {".dot",                    { 113, "application/msword" } },
        {".dotm",                   { 114, "application/vnd.ms-word.template.macroEnabled.12" } },
        {".dotx",                   { 115, "application/vnd.openxmlformats-officedocument.wordprocessingml.template" } },
        {".dsp",                    { 116, "application/octet-stream" } },
        {".dsw",                    { 117, "text/plain" } },
        {".dtd",                    { 118, "text/xml" } },
        {".dtsConfig",              { 119, "text/xml" } },
        {".dv",                     { 120, "video/x-dv" } },
        {".dvi",                    { 121, "application/x-dvi" } },
        {".dwf",                    { 122, "drawing/x-dwf" } },
        {".dwp",                    { 123, "application/octet-stream" } },
        {".dxr",                    { 124, "application/x-director" } },
        {".eml",                    { 125, "message/rfc822" } },
        {".emz",                    { 126, "application/octet-stream" } },
        {".eot",                    { 127, "application/vnd.ms-fontobject" } },
        {".eps",                    { 128, "application/postscript" } },
        {".etl",                    { 129, "application/etl" } },
        {".etx",                    { 130, "text/x-setext" } },
        {".evy",                    { 131, "application/envoy" } },
        {".exe",                    { 132, "application/octet-stream" } },
        {".exe.config",             { 133, "text/xml" } },
        {".fdf",                    { 134, "application/vnd.fdf" } },
        {".fif",                    { 135, "application/fractals" } },
        {".filters",                { 136, "application/xml" } },
        {".fla",                    { 137, "application/octet-stream" } },
        {".flac",                   { 138, "audio/flac" } },
        {".flr",                    { 139, "x-world/x-vrml" } },
        {".flv",                    { 140, "video/x-flv" } },
        {".fsscript",               { 141, "application/fsharp-script" } },
        {".fsx",                    { 142, "application/fsharp-script" } },
        {".generictest",            { 143, "application/xml" } },
        {".gif",                    { 144, "image/gif" } },
        {".gpx",                    { 145, "application/gpx+xml" } },
        {".group",                  { 146, "text/x-ms-group" } },
        {".gsm",                    { 147, "audio/x-gsm" } },
        {".gtar",                   { 148, "application/x-gtar" } },
        {".gz",                     { 149, "application/x-gzip" } },
        {".h",                      { 150, "text/plain" } },
        {".hdf",                    { 151, "application/x-hdf" } },
        {".hdml",                   { 152, "text/x-hdml" } },
        {".hhc",                    { 153, "application/x-oleobject" } },
        {".hhk",                    { 154, "application/octet-stream" } },
        {".hhp",                    { 155, "application/octet-stream" } },
        {".hlp",                    { 156, "application/winhlp" } },
        {".hpp",                    { 157, "text/plain" } },
        {".hqx",                    { 158, "application/mac-binhex40" } },
        {".hta",                    { 159, "application/hta" } },
        {".htc",                    { 160, "text/x-component" } },
        {".htm",                    { 161, "text/html" } },
        {".html",                   { 162, "text/html" } },
        {".htt",                    { 163, "text/webviewhtml" } },
        {".hxa",                    { 164, "application/xml" } },
        {".hxc",                    { 165, "application/xml" } },
        {".hxd",                    { 166, "application/octet-stream" } },
        {".hxe",                    { 167, "application/xml" } },
        {".hxf",                    { 168, "application/xml" } },
        {".hxh",                    { 169, "application/octet-stream" } },
        {".hxi",                    { 170, "application/octet-stream" } },
        {".hxk",                    { 171, "application/xml" } },
        {".hxq",                    { 172, "application/octet-stream" } },
        {".hxr",                    { 173, "application/octet-stream" } },
        {".hxs",                    { 174, "application/octet-stream" } },
        {".hxt",                    { 175, "text/html" } },
        {".hxv",                    { 176, "application/xml" } },
        {".hxw",                    { 177, "application/octet-stream" } },
        {".hxx",                    { 178, "text/plain" } },
        {".i",                      { 179, "text/plain" } },
        {".ico",                    { 180, "image/x-icon" } },
        {".ics",                    { 181, "application/octet-stream" } },
        {".idl",                    { 182, "text/plain" } },
        {".ief",                    { 183, "image/ief" } },
        {".iii",                    { 184, "application/x-iphone" } },
        {".inc",                    { 185, "text/plain" } },
        {".inf",                    { 186, "application/octet-stream" } },
        {".ini",                    { 187, "text/plain" } },
        {".inl",                    { 188, "text/plain" } },
        {".ins",                    { 189, "application/x-internet-signup" } },
        {".ipa",                    { 190, "application/x-itunes-ipa" } },
        {".ipg",                    { 191, "application/x-itunes-ipg" } },
        {".ipproj",                 { 192, "text/plain" } },
        {".ipsw",                   { 193, "application/x-itunes-ipsw" } },
        {".iqy",                    { 194, "text/x-ms-iqy" } },
        {".isp",                    { 195, "application/x-internet-signup" } },
        {".ite",                    { 196, "application/x-itunes-ite" } },
        {".itlp",                   { 197, "application/x-itunes-itlp" } },
        {".itms",                   { 198, "application/x-itunes-itms" } },
        {".itpc",                   { 199, "application/x-itunes-itpc" } },
        {".IVF",                    { 200, "video/x-ivf" } },
        {".jar",                    { 201, "application/java-archive" } },
        {".java",                   { 202, "application/octet-stream" } },
        {".jck",                    { 203, "application/liquidmotion" } },
        {".jcz",                    { 204, "application/liquidmotion" } },
        {".jfif",                   { 205, "image/pjpeg" } },
        {".jnlp",                   { 206, "application/x-java-jnlp-file" } },
        {".jpb",                    { 207, "application/octet-stream" } },
        {".jpe",                    { 208, "image/jpeg" } },
        {".jpeg",                   { 209, "image/jpeg" } },
        {".jpg",                    { 210, "image/jpeg" } },
        {".js",                     { 211, "application/javascript" } },
        {".json",                   { 212, "application/json" } },
        {".jsx",                    { 213, "text/jscript" } },
        {".jsxbin",                 { 214, "text/plain" } },
        {".latex",                  { 215, "application/x-latex" } },
        {".library-ms",             { 216, "application/windows-library+xml" } },
        {".lit",                    { 217, "application/x-ms-reader" } },
        {".loadtest",               { 218, "application/xml" } },
        {".lpk",                    { 219, "application/octet-stream" } },
        {".lsf",                    { 220, "video/x-la-asf" } },
        {".lst",                    { 221, "text/plain" } },
        {".lsx",                    { 222, "video/x-la-asf" } },
        {".lzh",                    { 223, "application/octet-stream" } },
        {".m13",                    { 224, "application/x-msmediaview" } },
        {".m14",                    { 225, "application/x-msmediaview" } },
        {".m1v",                    { 226, "video/mpeg" } },
        {".m2t",                    { 227, "video/vnd.dlna.mpeg-tts" } },
        {".m2ts",                   { 228, "video/vnd.dlna.mpeg-tts" } },
        {".m2v",                    { 229, "video/mpeg" } },
        {".m3u",                    { 230, "audio/x-mpegurl" } },
        {".m3u8",                   { 231, "audio/x-mpegurl" } },
        {".m4a",                    { 232, "audio/m4a" } },
        {".m4b",                    { 233, "audio/m4b" } },
        {".m4p",                    { 234, "audio/m4p" } },
        {".m4r",                    { 235, "audio/x-m4r" } },
        {".m4v",                    { 236, "video/x-m4v" } },
        {".mac",                    { 237, "image/x-macpaint" } },
        {".mak",                    { 238, "text/plain" } },
        {".man",                    { 239, "application/x-troff-man" } },
        {".manifest",               { 240, "application/x-ms-manifest" } },
        {".map",                    { 241, "text/plain" } },
        {".master",                 { 242, "application/xml" } },
        {".mda",                    { 243, "application/msaccess" } },
        {".mdb",                    { 244, "application/x-msaccess" } },
        {".mde",                    { 245, "application/msaccess" } },
        {".mdp",                    { 246, "application/octet-stream" } },
        {".me",                     { 247, "application/x-troff-me" } },
        {".mfp",                    { 248, "application/x-shockwave-flash" } },
        {".mht",                    { 249, "message/rfc822" } },
        {".mhtml",                  { 250, "message/rfc822" } },
        {".mid",                    { 251, "audio/mid" } },
        {".midi",                   { 252, "audio/mid" } },
        {".mix",                    { 253, "application/octet-stream" } },
        {".mk",                     { 254, "text/plain" } },
        {".mkv",                    { 255, "video/x-matroska" } },
        {".mmf",                    { 256, "application/x-smaf" } },
        {".mno",                    { 257, "text/xml" } },
        {".mny",                    { 258, "application/x-msmoney" } },
        {".mod",                    { 259, "video/mpeg" } },
        {".mov",                    { 260, "video/quicktime" } },
        {".movie",                  { 261, "video/x-sgi-movie" } },
        {".mp2",                    { 262, "video/mpeg" } },
        {".mp2v",                   { 263, "video/mpeg" } },
        {".mp3",                    { 264, "audio/mpeg" } },
        {".mp4",                    { 265, "video/mp4" } },
        {".mp4v",                   { 266, "video/mp4" } },
        {".mpa",                    { 267, "video/mpeg" } },
        {".mpe",                    { 268, "video/mpeg" } },
        {".mpeg",                   { 269, "video/mpeg" } },
        {".mpf",                    { 270, "application/vnd.ms-mediapackage" } },
        {".mpg",                    { 271, "video/mpeg" } },
        {".mpp",                    { 272, "application/vnd.ms-project" } },
        {".mpv2",                   { 273, "video/mpeg" } },
        {".mqv",                    { 274, "video/quicktime" } },
        {".ms",                     { 275, "application/x-troff-ms" } },
        {".msi",                    { 276, "application/octet-stream" } },
        {".mso",                    { 277, "application/octet-stream" } },
        {".mts",                    { 278, "video/vnd.dlna.mpeg-tts" } },
        {".mtx",                    { 279, "application/xml" } },
        {".mvb",                    { 280, "application/x-msmediaview" } },
        {".mvc",                    { 281, "application/x-miva-compiled" } },
        {".mxp",                    { 282, "application/x-mmxp" } },
        {".nc",                     { 283, "application/x-netcdf" } },
        {".nsc",                    { 284, "video/x-ms-asf" } },
        {".nws",                    { 285, "message/rfc822" } },
        {".ocx",                    { 286, "application/octet-stream" } },
        {".oda",                    { 287, "application/oda" } },
        {".odb",                    { 288, "application/vnd.oasis.opendocument.database" } },
        {".odc",                    { 289, "application/vnd.oasis.opendocument.chart" } },
        {".odf",                    { 290, "application/vnd.oasis.opendocument.formula" } },
        {".odg",                    { 291, "application/vnd.oasis.opendocument.graphics" } },
        {".odh",                    { 292, "text/plain" } },
        {".odi",                    { 293, "application/vnd.oasis.opendocument.image" } },
        {".odl",                    { 294, "text/plain" } },
        {".odm",                    { 295, "application/vnd.oasis.opendocument.text-master" } },
        {".odp",                    { 296, "application/vnd.oasis.opendocument.presentation" } },
        {".ods",                    { 297, "application/vnd.oasis.opendocument.spreadsheet" } },
        {".odt",                    { 298, "application/vnd.oasis.opendocument.text" } },
        {".oga",                    { 299, "audio/ogg" } },
        {".ogg",                    { 300, "audio/ogg" } },
        {".ogv",                    { 301, "video/ogg" } },
        {".ogx",                    { 302, "application/ogg" } },
        {".one",                    { 303, "application/onenote" } },
        {".onea",                   { 304, "application/onenote" } },
        {".onepkg",                 { 305, "application/onenote" } },
        {".onetmp",                 { 306, "application/onenote" } },
        {".onetoc",                 { 307, "application/onenote" } },
        {".onetoc2",                { 308, "application/onenote" } },
        {".opus",                   { 309, "audio/ogg" } },
        {".orderedtest",            { 310, "application/xml" } },
        {".osdx",                   { 311, "application/opensearchdescription+xml" } },
        {".otf",                    { 312, "application/font-sfnt" } },
        {".otg",                    { 313, "application/vnd.oasis.opendocument.graphics-template" } },
        {".oth",                    { 314, "application/vnd.oasis.opendocument.text-web" } },
        {".otp",                    { 315, "application/vnd.oasis.opendocument.presentation-template" } },
        {".ots",                    { 316, "application/vnd.oasis.opendocument.spreadsheet-template" } },
        {".ott",                    { 317, "application/vnd.oasis.opendocument.text-template" } },
        {".oxt",                    { 318, "application/vnd.openofficeorg.extension" } },
        {".p10",                    { 319, "application/pkcs10" } },
        {".p12",                    { 320, "application/x-pkcs12" } },
        {".p7b",                    { 321, "application/x-pkcs7-certificates" } },
        {".p7c",                    { 322, "application/pkcs7-mime" } },
        {".p7m",                    { 323, "application/pkcs7-mime" } },
        {".p7r",                    { 324, "application/x-pkcs7-certreqresp" } },
        {".p7s",                    { 325, "application/pkcs7-signature" } },
        {".pbm",                    { 326, "image/x-portable-bitmap" } },
        {".pcast",                  { 327, "application/x-podcast" } },
        {".pct",                    { 328, "image/pict" } },
        {".pcx",                    { 329, "application/octet-stream" } },
        {".pcz",                    { 330, "application/octet-stream" } },
        {".pdf",                    { 331, "application/pdf" } },
        {".pfb",                    { 332, "application/octet-stream" } },
        {".pfm",                    { 333, "application/octet-stream" } },
        {".pfx",                    { 334, "application/x-pkcs12" } },
        {".pgm",                    { 335, "image/x-portable-graymap" } },
        {".pic",                    { 336, "image/pict" } },
        {".pict",                   { 337, "image/pict" } },
        {".pkgdef",                 { 338, "text/plain" } },
        {".pkgundef",               { 339, "text/plain" } },
        {".pko",                    { 340, "application/vnd.ms-pki.pko" } },
        {".pls",                    { 341, "audio/scpls" } },
        {".pma",                    { 342, "application/x-perfmon" } },
        {".pmc",                    { 343, "application/x-perfmon" } },
        {".pml",                    { 344, "application/x-perfmon" } },
        {".pmr",                    { 345, "application/x-perfmon" } },
        {".pmw",                    { 346, "application/x-perfmon" } },
        {".png",                    { 347, "image/png" } },
        {".pnm",                    { 348, "image/x-portable-anymap" } },
        {".pnt",                    { 349, "image/x-macpaint" } },
        {".pntg",                   { 350, "image/x-macpaint" } },
        {".pnz",                    { 351, "image/png" } },
        {".pot",                    { 352, "application/vnd.ms-powerpoint" } },
        {".potm",                   { 353, "application/vnd.ms-powerpoint.template.macroEnabled.12" } },
        {".potx",                   { 354, "application/vnd.openxmlformats-officedocument.presentationml.template" } },
        {".ppa",                    { 355, "application/vnd.ms-powerpoint" } },
        {".ppam",                   { 356, "application/vnd.ms-powerpoint.addin.macroEnabled.12" } },
        {".ppm",                    { 357, "image/x-portable-pixmap" } },
        {".pps",                    { 358, "application/vnd.ms-powerpoint" } },
        {".ppsm",                   { 359, "application/vnd.ms-powerpoint.slideshow.macroEnabled.12" } },
        {".ppsx",                   { 360, "application/vnd.openxmlformats-officedocument.presentationml.slideshow" } },
        {".ppt",                    { 361, "application/vnd.ms-powerpoint" } },
        {".pptm",                   { 362, "application/vnd.ms-powerpoint.presentation.macroEnabled.12" } },
        {".pptx",                   { 363, "application/vnd.openxmlformats-officedocument.presentationml.presentation" } },
        {".prf",                    { 364, "application/pics-rules" } },
        {".prm",                    { 365, "application/octet-stream" } },
        {".prx",                    { 366, "application/octet-stream" } },
        {".ps",                     { 367, "application/postscript" } },
        {".psc1",                   { 368, "application/PowerShell" } },
        {".psd",                    { 369, "application/octet-stream" } },
        {".psess",                  { 370, "application/xml" } },
        {".psm",                    { 371, "application/octet-stream" } },
        {".psp",                    { 372, "application/octet-stream" } },
        {".pub",                    { 373, "application/x-mspublisher" } },
        {".pwz",                    { 374, "application/vnd.ms-powerpoint" } },
        {".qht",                    { 375, "text/x-html-insertion" } },
        {".qhtm",                   { 376, "text/x-html-insertion" } },
        {".qt",                     { 377, "video/quicktime" } },
        {".qti",                    { 378, "image/x-quicktime" } },
        {".qtif",                   { 379, "image/x-quicktime" } },
        {".qtl",                    { 380, "application/x-quicktimeplayer" } },
        {".qxd",                    { 381, "application/octet-stream" } },
        {".ra",                     { 382, "audio/x-pn-realaudio" } },
        {".ram",                    { 383, "audio/x-pn-realaudio" } },
        {".rar",                    { 384, "application/x-rar-compressed" } },
        {".ras",                    { 385, "image/x-cmu-raster" } },
        {".rat",                    { 386, "application/rat-file" } },
        {".rc",                     { 387, "text/plain" } },
        {".rc2",                    { 388, "text/plain" } },
        {".rct",                    { 389, "text/plain" } },
        {".rdlc",                   { 390, "application/xml" } },
        {".reg",                    { 391, "text/plain" } },
        {".resx",                   { 392, "application/xml" } },
        {".rf",                     { 393, "image/vnd.rn-realflash" } },
        {".rgb",                    { 394, "image/x-rgb" } },
        {".rgs",                    { 395, "text/plain" } },
        {".rm",                     { 396, "application/vnd.rn-realmedia" } },
        {".rmi",                    { 397, "audio/mid" } },
        {".rmp",                    { 398, "application/vnd.rn-rn_music_package" } },
        {".roff",                   { 399, "application/x-troff" } },
        {".rpm",                    { 400, "audio/x-pn-realaudio-plugin" } },
        {".rqy",                    { 401, "text/x-ms-rqy" } },
        {".rtf",                    { 402, "application/rtf" } },
        {".rtx",                    { 403, "text/richtext" } },
        {".ruleset",                { 404, "application/xml" } },
        {".s",                      { 405, "text/plain" } },
        {".safariextz",             { 406, "application/x-safari-safariextz" } },
        {".scd",                    { 407, "application/x-msschedule" } },
        {".scr",                    { 408, "text/plain" } },
        {".sct",                    { 409, "text/scriptlet" } },
        {".sd2",                    { 410, "audio/x-sd2" } },
        {".sdp",                    { 411, "application/sdp" } },
        {".sea",                    { 412, "application/octet-stream" } },
        {".searchConnector-ms",     { 413, "application/windows-search-connector+xml" } },
        {".setpay",                 { 414, "application/set-payment-initiation" } },
        {".setreg",                 { 415, "application/set-registration-initiation" } },
        {".settings",               { 416, "application/xml" } },
        {".sgimb",                  { 417, "application/x-sgimb" } },
        {".sgml",                   { 418, "text/sgml" } },
        {".sh",                     { 419, "application/x-sh" } },
        {".shar",                   { 420, "application/x-shar" } },
        {".shtml",                  { 421, "text/html" } },
        {".sit",                    { 422, "application/x-stuffit" } },
        {".sitemap",                { 423, "application/xml" } },
        {".skin",                   { 424, "application/xml" } },
        {".sldm",                   { 425, "application/vnd.ms-powerpoint.slide.macroEnabled.12" } },
        {".sldx",                   { 426, "application/vnd.openxmlformats-officedocument.presentationml.slide" } },
        {".slk",                    { 427, "application/vnd.ms-excel" } },
        {".sln",                    { 428, "text/plain" } },
        {".slupkg-ms",              { 429, "application/x-ms-license" } },
        {".smd",                    { 430, "audio/x-smd" } },
        {".smi",                    { 431, "application/octet-stream" } },
        {".smx",                    { 432, "audio/x-smd" } },
        {".smz",                    { 433, "audio/x-smd" } },
        {".snd",                    { 434, "audio/basic" } },
        {".snippet",                { 435, "application/xml" } },
        {".snp",                    { 436, "application/octet-stream" } },
        {".sol",                    { 437, "text/plain" } },
        {".sor",                    { 438, "text/plain" } },
        {".spc",                    { 439, "application/x-pkcs7-certificates" } },
        {".spl",                    { 440, "application/futuresplash" } },
        {".spx",                    { 441, "audio/ogg" } },
        {".src",                    { 442, "application/x-wais-source" } },
        {".srf",                    { 443, "text/plain" } },
        {".srt",                    { 444, "text/plain" } },
        {".SSISDeploymentManifest", { 445, "text/xml" } },
        {".ssm",                    { 446, "application/streamingmedia" } },
        {".sst",                    { 447, "application/vnd.ms-pki.certstore" } },
        {".stl",                    { 448, "application/vnd.ms-pki.stl" } },
        {".sub",                    { 449, "text/plain" } },
        {".sv4cpio",                { 450, "application/x-sv4cpio" } },
        {".sv4crc",                 { 451, "application/x-sv4crc" } },
        {".svc",                    { 452, "application/xml" } },
        {".svg",                    { 453, "image/svg+xml" } },
        {".swf",                    { 454, "application/x-shockwave-flash" } },
        {".t",                      { 455, "application/x-troff" } },
        {".tar",                    { 456, "application/x-tar" } },
        {".tcl",                    { 457, "application/x-tcl" } },
        {".testrunconfig",          { 458, "application/xml" } },
        {".testsettings",           { 459, "application/xml" } },
        {".tex",                    { 460, "application/x-tex" } },
        {".texi",                   { 461, "application/x-texinfo" } },
        {".texinfo",                { 462, "application/x-texinfo" } },
        {".tgz",                    { 463, "application/x-compressed" } },
        {".thmx",                   { 464, "application/vnd.ms-officetheme" } },
        {".thn",                    { 465, "application/octet-stream" } },
        {".tif",                    { 466, "image/tiff" } },
        {".tiff",                   { 467, "image/tiff" } },
        {".tlh",                    { 468, "text/plain" } },
        {".tli",                    { 469, "text/plain" } },
        {".toc",                    { 470, "application/octet-stream" } },
        {".tr",                     { 471, "application/x-troff" } },
        {".trm",                    { 472, "application/x-msterminal" } },
        {".trx",                    { 473, "application/xml" } },
        {".ts",                     { 474, "video/vnd.dlna.mpeg-tts" } },
        {".tsv",                    { 475, "text/tab-separated-values" } },
        {".ttf",                    { 476, "application/font-sfnt" } },
        {".tts",                    { 477, "video/vnd.dlna.mpeg-tts" } },
        {".txt",                    { 478, "text/plain" } },
        {".u32",                    { 479, "application/octet-stream" } },
        {".uls",                    { 480, "text/iuls" } },
        {".user",                   { 481, "text/plain" } },
        {".ustar",                  { 482, "application/x-ustar" } },
        {".vb",                     { 483, "text/plain" } },
        {".vbdproj",                { 484, "text/plain" } },
        {".vbk",                    { 485, "video/mpeg" } },
        {".vbproj",                 { 486, "text/plain" } },
        {".vbs",                    { 487, "text/vbscript" } },
        {".vcf",                    { 488, "text/x-vcard" } },
        {".vcproj",                 { 489, "application/xml" } },
        {".vcs",                    { 490, "text/plain" } },
        {".vcxproj",                { 491, "application/xml" } },
        {".vddproj",                { 492, "text/plain" } },
        {".vdp",                    { 493, "text/plain" } },
        {".vdproj",                 { 494, "text/plain" } },
        {".vdx",                    { 495, "application/vnd.ms-visio.viewer" } },
        {".vml",                    { 496, "text/xml" } },
        {".vscontent",              { 497, "application/xml" } },
        {".vsct",                   { 498, "text/xml" } },
        {".vsd",                    { 499, "application/vnd.visio" } },
        {".vsi",                    { 500, "application/ms-vsi" } },
        {".vsix",                   { 501, "application/vsix" } },
        {".vsixlangpack",           { 502, "text/xml" } },
        {".vsixmanifest",           { 503, "text/xml" } },
        {".vsmdi",                  { 504, "application/xml" } },
        {".vspscc",                 { 505, "text/plain" } },
        {".vss",                    { 506, "application/vnd.visio" } },
        {".vsscc",                  { 507, "text/plain" } },
        {".vssettings",             { 508, "text/xml" } },
        {".vssscc",                 { 509, "text/plain" } },
        {".vst",                    { 510, "application/vnd.visio" } },
        {".vstemplate",             { 511, "text/xml" } },
        {".vsto",                   { 512, "application/x-ms-vsto" } },
        {".vsw",                    { 513, "application/vnd.visio" } },
        {".vsx",                    { 514, "application/vnd.visio" } },
        {".vtx",                    { 515, "application/vnd.visio" } },
        {".wav",                    { 516, "audio/wav" } },
        {".wave",                   { 517, "audio/wav" } },
        {".wax",                    { 518, "audio/x-ms-wax" } },
        {".wbk",                    { 519, "application/msword" } },
        {".wbmp",                   { 520, "image/vnd.wap.wbmp" } },
        {".wcm",                    { 521, "application/vnd.ms-works" } },
        {".wdb",                    { 522, "application/vnd.ms-works" } },
        {".wdp",                    { 523, "image/vnd.ms-photo" } },
        {".webarchive",             { 524, "application/x-safari-webarchive" } },
        {".webm",                   { 525, "video/webm" } },
        {".webp",                   { 526, "image/webp" } },
        {".webtest",                { 527, "application/xml" } },
        {".wiq",                    { 528, "application/xml" } },
        {".wiz",                    { 529, "application/msword" } },
        {".wks",                    { 530, "application/vnd.ms-works" } },
        {".WLMP",                   { 531, "application/wlmoviemaker" } },
        {".wlpginstall",            { 532, "application/x-wlpg-detect" } },
        {".wlpginstall3",           { 533, "application/x-wlpg3-detect" } },
        {".wm",                     { 534, "video/x-ms-wm" } },
        {".wma",                    { 535, "audio/x-ms-wma" } },
        {".wmd",                    { 536, "application/x-ms-wmd" } },
        {".wmf",                    { 537, "application/x-msmetafile" } },
        {".wml",                    { 538, "text/vnd.wap.wml" } },
        {".wmlc",                   { 539, "application/vnd.wap.wmlc" } },
        {".wmls",                   { 540, "text/vnd.wap.wmlscript" } },
        {".wmlsc",                  { 541, "application/vnd.wap.wmlscriptc" } },
        {".wmp",                    { 542, "video/x-ms-wmp" } },
        {".wmv",                    { 543, "video/x-ms-wmv" } },
        {".wmx",                    { 544, "video/x-ms-wmx" } },
        {".wmz",                    { 545, "application/x-ms-wmz" } },
        {".woff",                   { 546, "application/font-woff" } },
        {".wpl",                    { 547, "application/vnd.ms-wpl" } },
        {".wps",                    { 548, "application/vnd.ms-works" } },
        {".wri",                    { 549, "application/x-mswrite" } },
        {".wrl",                    { 550, "x-world/x-vrml" } },
        {".wrz",                    { 551, "x-world/x-vrml" } },
        {".wsc",                    { 552, "text/scriptlet" } },
        {".wsdl",                   { 553, "text/xml" } },
        {".wvx",                    { 554, "video/x-ms-wvx" } },
        {".x",                      { 555, "application/directx" } },
        {".xaf",                    { 556, "x-world/x-vrml" } },
        {".xaml",                   { 557, "application/xaml+xml" } },
        {".xap",                    { 558, "application/x-silverlight-app" } },
        {".xbap",                   { 559, "application/x-ms-xbap" } },
        {".xbm",                    { 560, "image/x-xbitmap" } },
        {".xdr",                    { 561, "text/plain" } },
        {".xht",                    { 562, "application/xhtml+xml" } },
        {".xhtml",                  { 563, "application/xhtml+xml" } },
        {".xla",                    { 564, "application/vnd.ms-excel" } },
        {".xlam",                   { 565, "application/vnd.ms-excel.addin.macroEnabled.12" } },
        {".xlc",                    { 566, "application/vnd.ms-excel" } },
        {".xld",                    { 567, "application/vnd.ms-excel" } },
        {".xlk",                    { 568, "application/vnd.ms-excel" } },
        {".xll",                    { 569, "application/vnd.ms-excel" } },
        {".xlm",                    { 570, "application/vnd.ms-excel" } },
        {".xls",                    { 571, "application/vnd.ms-excel" } },
        {".xlsb",                   { 572, "application/vnd.ms-excel.sheet.binary.macroEnabled.12" } },
        {".xlsm",                   { 573, "application/vnd.ms-excel.sheet.macroEnabled.12" } },
        {".xlsx",                   { 574, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" } },
        {".xlt",                    { 575, "application/vnd.ms-excel" } },
        {".xltm",                   { 576, "application/vnd.ms-excel.template.macroEnabled.12" } },
        {".xltx",                   { 577, "application/vnd.openxmlformats-officedocument.spreadsheetml.template" } },
        {".xlw",                    { 578, "application/vnd.ms-excel" } },
        {".xml",                    { 579, "text/xml" } },
        {".xmta",                   { 580, "application/xml" } },
        {".xof",                    { 581, "x-world/x-vrml" } },
        {".XOML",                   { 582, "text/plain" } },
        {".xpm",                    { 583, "image/x-xpixmap" } },
        {".xps",                    { 584, "application/vnd.ms-xpsdocument" } },
        {".xrm-ms",                 { 585, "text/xml" } },
        {".xsc",                    { 586, "application/xml" } },
        {".xsd",                    { 587, "text/xml" } },
        {".xsf",                    { 588, "text/xml" } },
        {".xsl",                    { 589, "text/xml" } },
        {".xslt",                   { 590, "text/xml" } },
        {".xsn",                    { 591, "application/octet-stream" } },
        {".xss",                    { 592, "application/xml" } },
        {".xspf",                   { 593, "application/xspf+xml" } },
        {".xtp",                    { 594, "application/octet-stream" } },
        {".xwd",                    { 595, "image/x-xwindowdump" } },
        {".z",                      { 596, "application/x-compress" } },
        {".zip",                    { 597, "application/zip" } }
    }};

    inline const char *find_char(const char *string, const std::size_t size, char wanted)
    {
        const char *c = nullptr;
        if (size > 0)
        {
            for (int it = static_cast<int>(size) - 1; it >= 0; --it)
            {
                if (string[it] == wanted)
                {
                    c = &string[it];
                    break;
                }
            }
        }
        return c;
    }

    File::MIMEType mimeType(const std::string &name)
    {
        const char *fileName = name.c_str();
        auto extension = find_char(fileName, name.size(), '.');
        if (extension != nullptr)
        {
            auto it = mimeTypes.find(extension);
            if (it != mimeTypes.end())
            {
                return it->second;
            }
            else
            {
                return { -1, "" };
            }
        }
        else
        {
            return { -1, "" };
        }
    }
}

File::File(std::string &&name,
           std::uint64_t bytesCompleted,
           std::uint64_t bytesTotal,
           bool wanted,
           File::Priority priority) :
    id_(0),
    name_(std::move(name)),
    bytesCompleted_(bytesCompleted),
    bytesTotal_(bytesTotal),
    wanted_(wanted),
    priority_(priority),
    type_(mimeType(name_))
{
}

const std::string &File::name() const
{
    return name_;
}

uint64_t File::bytesCompleted() const
{
    return bytesCompleted_;
}

uint64_t File::bytesTotal() const
{
    return bytesTotal_;
}

bool File::wanted() const
{
    return wanted_;
}

File::Priority File::priority() const
{
    return priority_;
}

File::MIMEType File::type() const
{
    return type_;
}
