if (CMAKE_CXX_COMPILER_ID MATCHES "Clang" OR CMAKE_CXX_COMPILER_ID MATCHES "GNU")
    include (CheckCXXCompilerFlag)
    CHECK_CXX_COMPILER_FLAG ("-std=c++14" COMPILER_SUPPORTS_CXX14)
    if (COMPILER_SUPPORTS_CXX14)
	    set (GEARBOX_COMPILER_FLAGS "${GEARBOX_COMPILER_FLAGS} -std=c++14")
    else ()
        message (WARNING "The compiler ${CMAKE_CXX_COMPILER} has no C++14 support. Please use a different C++ compiler.")
		set (GEARBOX_BAD_COMPILER 1)
    endif ()
elseif (CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
    if (CMAKE_CXX_COMPILER_VERSION VERSION_LESS 19.0)
        message(WARNING "The minimum required version of Visual Studio is 2015")
		set (GEARBOX_BAD_COMPILER 1)
    endif ()
else ()
    message (WARNING "${CMAKE_CXX_COMPILER} is not currently supported.")
    set (GEARBOX_BAD_COMPILER 1)
endif ()

if (GEARBOX_BAD_COMPILER AND NOT GEARBOX_ALLOW_UNSUPPORTED_COMPILER)
    message (FATAL_ERROR "Stopping since RT_ALLOW_UNSUPPORTED_COMPILER is not set")
endif ()

