if (CMAKE_CXX_COMPILER_ID MATCHES "Clang" OR CMAKE_CXX_COMPILER_ID MATCHES "GNU")
    include (CheckCXXCompilerFlag)
    CHECK_CXX_COMPILER_FLAG ("-std=c++14" COMPILER_SUPPORTS_CXX14)
    CHECK_CXX_COMPILER_FLAG ("-std=c++1y" COMPILER_SUPPORTS_CXX1Y)
    if (COMPILER_SUPPORTS_CXX14)
	    set (GEARBOX_COMPILER_FLAGS "${GEARBOX_COMPILER_FLAGS} -std=c++14")
    elseif (COMPILER_SUPPORTS_CXX1Y)
	    set (GEARBOX_COMPILER_FLAGS "${GEARBOX_COMPILER_FLAGS} -std=c++1y")
    else ()
        message (FATAL_ERROR "The compiler ${CMAKE_CXX_COMPILER} has no C++14 support. Please use a different C++ compiler.")
    endif ()
elseif (CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
    # check compiler is at least Visual Studio 2015
else ()
    message (WARNING "${CMAKE_CXX_COMPILER} is not currently supported.")
    if (NOT GEARBOX_ALLOW_UNSUPPORTED_COMPILER)
        message (FATAL_ERROR "Stopping since RT_ALLOW_UNSUPPORTED_COMPILER is not set")
    endif ()
endif ()

